import os
import sys
import subprocess
import pandas as pd


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python analytics.py <csv-path>")
        sys.exit(1)

    input_path = sys.argv[1]
    df = pd.read_csv(input_path)

    total_customers = len(df)
    avg_spend = df["total_spend"].mean()
    median_orders = df["order_count"].median()
    revenue_share_top_10 = (
        df.nlargest(10, "total_spend")["total_spend"].sum() / df["total_spend"].sum() * 100
    )

    country_summary = (
        df.groupby("dominant_country")
        .agg(customers=("CustomerID", "count"), revenue=("total_spend", "sum"))
        .sort_values(["customers", "revenue"], ascending=False)
    )
    top_country = country_summary.index[0]
    top_country_customers = int(country_summary.iloc[0]["customers"])
    top_country_revenue = float(country_summary.iloc[0]["revenue"])

    segment_summary = (
        df.groupby("spend_segment", observed=False)
        .agg(customers=("CustomerID", "count"), avg_spend=("total_spend", "mean"))
        .sort_values("avg_spend", ascending=False)
    )
    highest_segment = segment_summary.index[0]

    behavior_summary = (
        df.groupby("frequency_segment", observed=False)
        .agg(avg_orders=("order_count", "mean"), avg_recency=("recency_days", "mean"))
        .round(2)
    )

    insight1 = (
        f"Customer base summary\n"
        f"- Total customers after preprocessing: {total_customers}\n"
        f"- Average customer spend: {avg_spend:.2f}\n"
        f"- Median number of orders per customer: {median_orders:.0f}\n"
        f"- Top 10 customers contribute {revenue_share_top_10:.2f}% of total spend.\n"
    )

    insight2 = (
        f"Country concentration\n"
        f"- The largest customer base comes from {top_country}.\n"
        f"- Customers in this country: {top_country_customers}\n"
        f"- Revenue generated by this country: {top_country_revenue:.2f}\n\n"
        f"Top 5 countries by customer count and revenue:\n"
        f"{country_summary.head(5).to_string()}\n"
    )

    insight3 = (
        f"Segment behavior\n"
        f"- The highest-value spend segment is: {highest_segment}.\n\n"
        f"Average order behavior by frequency segment:\n"
        f"{behavior_summary.to_string()}\n"
    )

    for idx, content in enumerate([insight1, insight2, insight3], start=1):
        with open(os.path.join(os.getcwd(), f"insight{idx}.txt"), "w", encoding="utf-8") as f:
            f.write(content)

    print("Analytics insights generated successfully.")
    subprocess.run([sys.executable, "visualize.py", input_path], check=True)
